spring:
  datasource:
    url: jdbc:sqlserver://expense1.database.windows.net:1433;database=expense1;user=admin123@expense1;password=Harvey@003501; encrypt=true; trustServer Certificate=false; hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect